version: "3.8"

services:
  server:

    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    ports:
      - '8000:80'
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - mysql
    networks:
      - php-for-beginners

  php:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated
    networks:
      - php-for-beginners

  mysql:
    image: mysql:latest
    env_file:
      - ./env/mysql.env
    networks:
      - php-for-beginners

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - '8001:80'
    env_file:
      - ./env/phpmyadmin.env
    networks:
      - php-for-beginners

networks:
  php-for-beginners:
    driver: bridge